In [1]:
import torch
print(torch.__version__)


1.11.0


In [3]:
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor, Lambda, Compose
import matplotlib.pyplot as plt
import numpy as np

In [19]:
#Tensor: 배열이나 행렬과 매우 유사한 자료구조, Pytorch는 Tensor를 기본적으로 사용함

In [20]:
#1.list로 부터 직접 Tensor생성하기

In [23]:
data=[[1,2],[3,4]]
print(data)
print(type(data)) #list형태의 data 생성

[[1, 2], [3, 4]]
<class 'list'>


In [25]:
x_data=torch.tensor(data)
print(x_data)
print(type(x_data))

tensor([[1, 2],
        [3, 4]])
<class 'torch.Tensor'>


In [26]:
#2.np.array->tensor

In [28]:
data1=np.array(data)
print(data1)
type(data1)

[[1 2]
 [3 4]]


numpy.ndarray

In [31]:
x_data1=torch.tensor(data1)
print(x_data1)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [32]:
x_data2=torch.as_tensor(data1)
print(x_data2)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [33]:
x_data3=torch.from_numpy(data1)
print(x_data3)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [34]:
x_data1[0,0]=5
print(x_data1)
print(data1)

tensor([[5, 2],
        [3, 4]], dtype=torch.int32)
[[1 2]
 [3 4]]


In [39]:
x_data2[0,0]=6
print(x_data1)
print(data1) #원래 array값의 값도 같이 바뀜

tensor([[6, 2],
        [3, 4]], dtype=torch.int32)
[[6 2]
 [3 4]]


In [41]:
x_data3[0,0]=7
print(x_data1)
print(data1) #마찬가지로 array값도 같이바뀜

tensor([[6, 2],
        [3, 4]], dtype=torch.int32)
[[7 2]
 [3 4]]


In [42]:
###numpy로바꾸기
np_again=x_data1.numpy()
print(np_again,type(np_again))

[[6 2]
 [3 4]] <class 'numpy.ndarray'>


In [44]:
####tensor 다루기
a=torch.ones(2,3)
b=torch.zeros(2,3)
c=torch.full((2,3),2)
d=torch.empty(2,3)
print(a)
print(b)
print(c)
print(d)


tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[2, 2, 2],
        [2, 2, 2]])
tensor([[2.1155e+23, 1.2801e-11, 2.5813e-09],
        [8.3748e-10, 1.3107e-08, 6.3008e-10]])


In [45]:
e=torch.zeros_like(c)
f=torch.ones_like(c)
g=torch.full_like(c,3)
h=torch.empty_like(c)
print(e)
print(f)
print(g)
print(h)

tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([[1, 1, 1],
        [1, 1, 1]])
tensor([[3, 3, 3],
        [3, 3, 3]])
tensor([[0, 0, 0],
        [0, 0, 0]])


In [46]:
j=torch.arange(10)
print(j)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [49]:
#random number만들기
k=torch.rand(2,2) 
l=torch.randn(2,2)
print(k)
print(l)

tensor([[0.7350, 0.8558],
        [0.8511, 0.3001]])
tensor([[ 1.6345, -1.9001],
        [-1.2538,  0.1960]])


In [60]:
#Tensor 속성
tensor=torch.rand(3,4)
print(tensor)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)


tensor([[0.0429, 0.6482, 0.1258, 0.5770],
        [0.4023, 0.2337, 0.0664, 0.0633],
        [0.0483, 0.0647, 0.2109, 0.4404]])
torch.Size([3, 4])
torch.float32
cpu


In [62]:
#속성변경
tensor=tensor.reshape(4,3)
print(tensor)

if torch.cuda.is_available():
    tensor=tensor.to('cuda') #gpu로 변경
    
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

tensor([[0.0429, 0.6482, 0.1258],
        [0.5770, 0.4023, 0.2337],
        [0.0664, 0.0633, 0.0483],
        [0.0647, 0.2109, 0.4404]])
torch.Size([4, 3])
torch.float32
cuda:0


In [63]:
#indexing sliceing

a=torch.arange(1,13).reshape(3,4)
print(a)

#indexing
print(a[1])
print(a[0,-1])

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
tensor([5, 6, 7, 8])
tensor(4)


In [76]:
#slicing
print(a[1:3])
print(a[1,-3])

tensor([[ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
tensor(6)


In [77]:
#slicing
print(a[1:-1])
print(a[:2,2:])

tensor([[5, 6, 7, 8]])
tensor([[3, 4],
        [7, 8]])


In [78]:
#Transpose

a=torch.arange(16).reshape(2,2,4)

In [82]:
print(a,a.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]]]) torch.Size([2, 2, 4])


In [80]:
b=a.transpose(1,2) #2와 4를 바꿔서->torch.size([2,2,4])->torch.size(2,4,2)로 바꿔줌
print(b,b.shape)

tensor([[[ 0,  4],
         [ 1,  5],
         [ 2,  6],
         [ 3,  7]],

        [[ 8, 12],
         [ 9, 13],
         [10, 14],
         [11, 15]]]) torch.Size([2, 4, 2])


In [89]:
c=a.permute((2,0,1))
print(c,c.shape)

tensor([[[ 0,  4],
         [ 8, 12]],

        [[ 1,  5],
         [ 9, 13]],

        [[ 2,  6],
         [10, 14]],

        [[ 3,  7],
         [11, 15]]]) torch.Size([4, 2, 2])


In [90]:
#Tensor연산

x=torch.tensor([[1,2],[3,4]],dtype=torch.float32)
y=torch.tensor([[5,6],[7,8]],dtype=torch.float32)
print(x)
print(y)

tensor([[1., 2.],
        [3., 4.]])
tensor([[5., 6.],
        [7., 8.]])


In [92]:
print(x+y)
print(x-y)
print(x*y)
print(x/y)

tensor([[ 6.,  8.],
        [10., 12.]])
tensor([[-4., -4.],
        [-4., -4.]])
tensor([[ 5., 12.],
        [21., 32.]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])


In [93]:
print(x@y)

tensor([[19., 22.],
        [43., 50.]])


In [94]:
z=torch.arange(1,11).reshape(2,5)
print(z)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])


In [95]:
sum1=torch.sum(z,axis=0)
print(sum1)

tensor([ 7,  9, 11, 13, 15])


In [96]:
sum2=torch.sum(z,axis=1)
print(sum2)

tensor([15, 40])


In [98]:
sum3=torch.sum(z,axis=-1)
print(sum3,sum3.shape)

tensor([15, 40]) torch.Size([2])


In [101]:
#torch 복사
a=torch.arange(24).reshape(4,6)
print(a)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])


In [104]:
b=a.clone().detach()
print(a,a.shape)
print(b,b.shape)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]) torch.Size([4, 6])
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]) torch.Size([4, 6])


In [105]:
#concat, stack
#concat=cat함수는 concatenate를 해주는 함수이고 concatenate하고자 하는 차원을 증가시킨다->tensor합치기라고 생각
#stack=stack함수는 지정하는 차원으로 확장하여 tensor를 쌓아주는 함수이다. (지정하는 차원에 새로운 차원이 생긴다=차원의 수가 증가한다)

In [106]:
c=torch.cat([a,b],axis=0) #행기준으로 rowbind

In [107]:
print(c)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])


In [110]:
c=torch.cat([a,b],axis=-1) #열기준으로 rowbind

In [111]:
print(c)

tensor([[ 0,  1,  2,  3,  4,  5,  0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 18, 19, 20, 21, 22, 23]])


In [117]:
d=torch.stack([a,b],axis=0)
print(d,d.shape) #2개의 4x6 tensor

tensor([[[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11],
         [12, 13, 14, 15, 16, 17],
         [18, 19, 20, 21, 22, 23]],

        [[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11],
         [12, 13, 14, 15, 16, 17],
         [18, 19, 20, 21, 22, 23]]]) torch.Size([2, 4, 6])


In [118]:
d=torch.stack([a,b],axis=1)
print(d,d.shape) #4개의 2x6 tensor

tensor([[[ 0,  1,  2,  3,  4,  5],
         [ 0,  1,  2,  3,  4,  5]],

        [[ 6,  7,  8,  9, 10, 11],
         [ 6,  7,  8,  9, 10, 11]],

        [[12, 13, 14, 15, 16, 17],
         [12, 13, 14, 15, 16, 17]],

        [[18, 19, 20, 21, 22, 23],
         [18, 19, 20, 21, 22, 23]]]) torch.Size([4, 2, 6])


In [119]:
d=torch.stack([a,b],axis=-1)
print(d,d.shape)

tensor([[[ 0,  0],
         [ 1,  1],
         [ 2,  2],
         [ 3,  3],
         [ 4,  4],
         [ 5,  5]],

        [[ 6,  6],
         [ 7,  7],
         [ 8,  8],
         [ 9,  9],
         [10, 10],
         [11, 11]],

        [[12, 12],
         [13, 13],
         [14, 14],
         [15, 15],
         [16, 16],
         [17, 17]],

        [[18, 18],
         [19, 19],
         [20, 20],
         [21, 21],
         [22, 22],
         [23, 23]]]) torch.Size([4, 6, 2])
